feat: set api key basic command (#4)
* build: test self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix self test

* fix: clean up unneeded debugging content

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -5,7 +5,7 @@ branding:
   icon: activity
   color: blue
 inputs:
-  openAiKey:
+  openAiApiKey:
     description: 'OpenAI API Key'
     required: true
   command:
@@ -15,6 +15,12 @@ inputs:
 runs:
   using: composite
   steps:
+    - name: Verify Parameters
+      shell: bash
+      run: |
+        [[ ! -z '${{ inputs.openAiApiKey }}' ]] || { echo "'openAiApiKey' parameter is required" ; exit 1; }
+        [[ ! -z '${{ inputs.command }}' ]] || { echo "'command' parameter is required" ; exit 1; }
+
     - name: Setup Node
       uses: actions/setup-node@v4
       with:
@@ -25,15 +31,13 @@ runs:
       shell: bash
       run: npm install -g @dwmkerr/terminal-ai
 
-    - name: create ~/.ai/config.yaml
+    - name: Create Config File & Set API Key
       shell: bash
-      run:
-        echo "openaikey: ${{ inputs.openaikey }} >> ~/.ai/config.yaml"
+      run: |
+        mkdir ~/.ai
+        echo "openAiApiKey: ${{ inputs.openAiApiKey }}" >> ~/.ai/config.yaml
 
-    - name: Debug Config
+    - name: Test Command
       shell: bash
-      run: cat ~/.ai/config.yaml
-
-    - name: Execute Command
-      shell: bash
-      run: ${{ inputs.command }}
+      run: |
+        ${{ inputs.command }}
